CLASS zosa_cl_git DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
   INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zosa_cl_git IMPLEMENTATION.
 METHOD if_oo_adt_classrun~main.
out->write( 'test' ).
ENDMETHOD.
ENDCLASS.
